### ISSUE TITLE
Transpose support

### ISSUE THREAD

**Issue by strk** [billthefarmer/tuner#15]
As I started using this great app with a Bb trumpet, I was thinking it would be great to have support for transposing the displayed note so it matches the one written on a non-C score. Is that something you'd consider adding ? I might try to implement it myself, if time permits, but could be something simple for someone who knows the codebase

**Comment by billthefarmer** [comment]
I will look at adding a transpose item to the settings.

**Comment by billthefarmer** [comment]
Ok, that works, I think. I just want to check I've got it right before I release it, as I've never played a transposing instrument for real. If you play Bb, and set the transpose option to -2(Bb), the tuner shows C. With no input, the tuner shows D, so you know you've got the transposition on.

**Comment by strk** [comment]
Works for me, but as I'm new to the trumpet, will ask others
to give their comments about whether "-2" is a good way to express
that (I'd think +2, but maybe there's an standard notation)

**Comment by billthefarmer** [comment]
I think you're probably right, I'm just firing up an ancient iPhone that has an equally old version of iStroboSoft with drop capo/transpose on it to see what that does.

**Comment by strk** [comment]
-2 makes sense if it means
"my instrument is 2 semitones below written note"

+2 if it means
"please show me 2 semitones above what you hear"

so it depends on what the label says.
@dmbaturin (on IRC nick in freenode) expressed the desire of
even having nicknames for known instruments, like "Bb trumpet",
which would be more similar to the first approach (ie: I tell
the app what instrument I'm playing).

**Comment by billthefarmer** [comment]
I checked the iStroboSoft  app and it agrees with me. I am changing the items in the list to -2[Key:Bb] etc. I don't think the instrument would help, I had a Bb euphonium once, and I know a clarinet can be Bb and a lot of other instruments as well. And you can get Bb, C, and Eb saxophones.

**Comment by strk** [comment]
Sold ! :)

**Comment by strk** [comment]
Hey @billthefarmer ... I noticed that the top-bar of the Tuner says "Equal Temperament C" even when transposed, what's the "C" supposed to represent then ? Should it be "Bb" when transposed to `-2[Key:Bb]` instead ?

**Comment by billthefarmer** [comment]
If you use a temperament other than equal you need to specify the key. In equal temperament you can set that to whatever you want.
