### ISSUE TITLE
filter input

### ISSUE THREAD

**Issue by alekksander** [billthefarmer/tuner#17]
how can we filter what comes in, so the tuner is more calm and instrument easier to tune, just like i've seen in non—free software?
i guess this is more of a feature request :)

**Comment by billthefarmer** [comment]
There are two build in functions for that, a low pass filter which can be turned on and off by touching the scope panel, and downsampling, which can be turned on and off by a long touch on the spectrum panel. They are also in the settings.

**Comment by alekksander** [comment]
but even with these two i can't tune any of my string instruments correctly. the result gets crazy and interfere with all ambient sounds.

**Comment by billthefarmer** [comment]
I didn't particularly design this tuner with string instruments in mind. It's intended for accordions with multiple reeds to show all the reeds. However I just went and got my banjo, which is pretty bongy, and if you put the phone microphone near the diaphragm/sound hole so it picks up more of the fundamental, it does work. It won't work like the sound conduction tuners that all the string instrument players I know use, by clipping it to the tuning head of the instrument.
However there is no shortage of tuner apps out there. The best one I've tried is the [Peterson iStroboSoft](https://www.petersontuners.com/products/istrobosoft/). You have to pay real money for it, but it must be cheaper than one of those clip on ones.

**Comment by alekksander** [comment]
i put my interest in this application mostly because it is open source, which is usually my main determinant. if it's designed for other type of instruments, i guess there is no point of asking for better string support.
thank You for clarifying and the other suggestion.

**Comment by billthefarmer** [comment]
Another thing to try if you can't get a stable display is to reboot the phone. I wanted to do some tuner screenshots on my phone yesterday and it wouldn't co-operate at all, but I had been using it for testing audio apps all day. Today I tried again and it worked perfectly.

**Comment by malberts** [comment]
@alekksander I know this is an old issue, but have a look at the experimental release here:
https://github.com/billthefarmer/tuner/releases/tag/v1.20

@billthefarmer has added some filters that I needed specifically to hide all those jumpy/wrong notes. Although I am using it or accordion tuning, maybe the new filters will help you as well.

**Comment by alekksander** [comment]
@malberts 
Thank You, will check it out.
