### ISSUE TITLE
Add back button to note filter activity

### ISSUE THREAD

**Issue by malberts** [billthefarmer/tuner#24]
This issue applies to the filter branch: https://github.com/billthefarmer/tuner/tree/filter/

There is a small usability issue where there is no back button in the toolbar when setting the note filters:
![image](https://user-images.githubusercontent.com/1428594/37084914-685ea9c8-21fc-11e8-8ee1-8a8ac3a8f41e.png)

Issue source: https://accordionists.co.uk/viewtopic.php?f=3&t=5561#p55917

**Comment by billthefarmer** [comment]
This is an Android issue. Up to android 4 the back button in the toolbar had an id - android.R.id.home, so I could attach a listener to it - [here](https://github.com/billthefarmer/tuner/blob/master/src/main/java/org/billthefarmer/tuner/SettingsFragment.java#L146), and enable the back button. But when they moved to Material design they removed the id, so I could enable the button, but it won't do anything, so I took the code out.

I agree, it's annoying, but it's the same in all my apps with nested preferences.
