### ISSUE TITLE
Add do ré mi scale

### ISSUE THREAD

**Issue by roptat** [billthefarmer/tuner#28]
Hi,

I usually use the French do ré mi scale instead of the A B C scale. I'd be very happy if there was an option to use that scale.

```
A -> La
B -> Si
C -> Do
D -> Ré
E -> Mi
F -> Fa
G -> Sol
```

**Comment by roptat** [comment]
Hi,

Why did you close this? Did you impliment it or is this a won't fix?

**Comment by billthefarmer** [comment]
That was a mistake. I have implemented this, but only on the main display, as it causes overlap otherwise. That will be in the next version.

**Comment by roptat** [comment]
thank you!
