### ISSUE TITLE
"Settings" causes app to crash

### ISSUE THREAD

**Issue by LuccoJ** [billthefarmer/tuner#31]
Using a fresh install of version 1.24 from F-Droid, trying to go into Settings ("gear" icon) causes an immediate force close of the app on my LineageOS 15.1 (ZTE Axon 7).

**Comment by LuccoJ** [comment]
I'm afraid with version 1.25 that showed up in F-Droid today, the problem is still present for me, even after clearing app data.

**Comment by billthefarmer** [comment]
Sometimes F-Droid take a long time to publish new releases. This bug was reported just after I pushed version 1.25, only just now published. The fix is in version 1.26, pushed on the 10th. I have pushed another version since, with an enhancement.

**Comment by billthefarmer** [comment]
Looks like they didn't bother with 1.26, they've now released 1.27.

**Comment by LuccoJ** [comment]
Well, the issue is fixed in 1.27 now available in F-Droid. Thanks.
