### ISSUE TITLE
[idea] allow for user-specified temperaments

### ISSUE THREAD

**Issue by codingWhatzThat** [billthefarmer/tuner#34]
This tuner app is the most complete I've yet stumbled upon.  One possible addition it still seems to lack, however:  I've used an android app from the google repository which also allows for other temperaments, even allowing user-specified frequency deviations in cents plus two decimal places from the equal tempered chromatic scale.  I'm looking to tune to Pythagorean tuning values and Chinese tunings also.  If this functionality could be worked into this already well established offering, it would indeed make it, so far as I've known anything of, the most complete manifestation of its kind.

I'm new to the subject of alternatives to the equal tempered tuning, and from what I've started to gather, an ability to input actual wave frequencies as opposed to inputing cents deviation might be a more precise and direct method of achieving software sensitivity to the desired frequencies for other temperaments as the relationships with these other tunings are a matter of arriving at products of rational numbers and a base frequency.  How the relationships between the octaves are handled with regard to tuning and what I'm learning is called Pythagorean comma, is something that's still beyond me just at present.  I'm just not sure, yet, how the pitches outside of the octave of the reference frequency are calculated, while I have seen regarding Chinese tuning, a chart of ratios from the fundamental, carrying up a note at a time, each new scale of sorts basing from one of the twelve calculated pitches of the base octave.  How multiple octaves are handled with such tunings is more than I personally could advise about to date.

What do you think?  Could this be of interest to you as an inclusion to your Tuner software?

**Comment by billthefarmer** [comment]
I looked at this a long time ago when I developed the first version of this app. I will have another look.

**Comment by codingWhatzThat** [comment]
Bill,

Thanks much,

Stephen

----- Original Message -----

**Comment by billthefarmer** [comment]
OK, that appears to work, it will be in the next version.

**Comment by codingWhatzThat** [comment]
Great!  I look forward to it!

I'm not sure I follow how the table of Chinese octave frequencies I found can be implemented yet, but I'll wait to see what you've done, and if there are further changes necessary for those tones, I can make another idea suggestion after I've come to understand better what I'll need to mention.

Thank you so much for your work!

**Comment by billthefarmer** [comment]
It would be possible to add user defined temperaments stored in a simple text file.
```properties
# User Temperaments
Pythagorean: 1.000000000, 1.067871094, 1.125000000, 1.185185185, \
             1.265625000, 1.333333333, 1.423828125, 1.500000000, \
             1.601806641, 1.687500000, 1.777777778, 1.898437500
```
There would need to be 12 values for each temperament, which can be simple ratios, like the example, or actual frequencies. All that matters is the ratios within each list. There is built in functionality to read a property list like this.

**Comment by codingWhatzThat** [comment]
This way works!

# Custom Temperaments 
Chinese: 1.000000000, 1.067871094, 1.125000000, 1.207361963, 1.265625000, 1.350877193, 1.423828125, 1.500000000, 1.601806641, 1.687500000, 1.801953006, 1.898437500

**Comment by billthefarmer** [comment]
OK, thanks

**Comment by raboof** [comment]
(I was surprised to see the latest version of the tuner require SD card access - but reading up it is not really possible to postpone requiring this permission without sacrificing support for older Android versions so I created a separate issue (#35))

**Comment by billthefarmer** [comment]
It's not possible to check for a user provided file without permission to read external storage or SD card according to the device. It would be possible for the user file to be in the app's external files directory (`Android/data/<app id>/files`), which doesn't need permission, but this is deleted if the app is uninstalled. If you deny permission, possible in LineageOS, you just don't get the custom temperaments as the app assumes no file.

**Comment by raboof** [comment]
Hmm, having to re-upload any custom temperaments after app uninstall/reinstall sounds like a relatively small price to pay if it allows not requiring the 'SD card' permission... but this is obviously up to you to decide :smile:
