### ISSUE TITLE
Change Key without going into settings & Disable Key

### ISSUE THREAD

**Issue by trymeouteh** [billthefarmer/tuner#36]
Please add an change the key without going into the settings and add an option to disable the key. The disable key option will make this app handy for vocalist who want to see if they are on pitch or not.

**Comment by billthefarmer** [comment]
The key is part of the temperaments function and only makes a slight difference if a temperament other than equal is selected. It is shown in the action bar so users can see they have changed the temperament or key. There is no concept of key in the tuner in equal temperament in the context you mention.
