### ISSUE TITLE
Why "accordion tuner"?

### ISSUE THREAD

**Issue by ahstro** [billthefarmer/tuner#37]
I've been using this app to tune guitars for a while and it's been working fine, but I keep seeing the phrase "accordion tuner" all over and I'm curious: Why? Does this app cater specifically to accordions in some way I'm not familiar with? I'm not that knowledgeable about music, so I might be overlooking something obvious.

**Comment by billthefarmer** [comment]
You can use it to tune any musical instrument, but I did develop it with accordions in mind. Most accordions except very small ones have more than one reed per key/button. Thats why the spectrum view will show up to eight separate notes so you can tune all the reeds at the same time and get the vibrato/tremolo/wetness just as you want it. If you, on your guitar, play two strings with nearly the same note you should see them show up on the display.
