### ISSUE TITLE
crash when enabling audio.lock

### ISSUE THREAD

**Issue by mbakhoff** [billthefarmer/tuner#4]
The application crashes when I click on the cents error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
    at org.billthefarmer.tuner.Display.onDraw(Display.java:126)
    at android.view.View.draw(View.java:15114)
```
I'm running Tuner 1.0.7 from f-droid (cyanogenmod12/android5.0.2). 
Let me know if I can help with debugging in any way :)

**Comment by mbakhoff** [comment]
Ok, so I digged around a bit: 
This is the failing line: 
```
bitmap = BitmapFactory.decodeResource(resources, android.R.drawable.ic_lock_lock);
```
Using this works fine (at least when I poke it in the debugger): 
```
bitmap = ((BitmapDrawable) resources.getDrawable(android.R.drawable.ic_lock_lock)).getBitmap();
```
Digging deeper, it looks like a similar line in Meter.java works fine:
```
bitmap = BitmapFactory.decodeResource(resources, R.drawable.ic_pref_screen);
```

The only difference that I found is this:
```
TypedValue pref = new TypedValue();
resources.openRawResource(R.drawable.ic_pref_screen, pref);
pref.toString() => TypedValue{t=0x3/d=0x45 "res/drawable-xhdpi-v4/ic_pref_screen.png" a=2 r=0x7f02000c}
TypedValue lock = new TypedValue();
resources.openRawResource(android.R.drawable.ic_lock_lock, lock);
lock.toString() => TypedValue{t=0x3/d=0x26d "res/drawable/ic_lock_lock.xml" a=1 r=0x108002f}
```

I would say it doesn't want to open a bitmap from a xml drawable, but png drawable is fine. I have no idea how or why it works like this..

**Comment by billthefarmer** [comment]
This looks like a possible timing issue on your device. I can't reproduce it on the devices I use for testing, a Nexus 7 and a Moto G. I will investigate tightening up the code.

**Comment by billthefarmer** [comment]
Having had a look at the code I see I used an android resource rather than the icon file sitting in the resources ready to be used. I don't know why I did that. Perhaps later versions of Android don't have that resource. I will post a new version which will appear on F-droid in a day or so.

**Comment by mbakhoff** [comment]
1.08 from f-droid no longer crashes. awesome! thanks for the fix and the app!
