### ISSUE TITLE
app state is lost on activity restarting 

### ISSUE THREAD

**Issue by ufarooq** [billthefarmer/tuner#41]
version: 1.33

Open the app, tap on the centre area, "lock" will appear and message display lock on, restart the activity by splitting the screen, "lock" state and icon are lost after restarting.

**Comment by billthefarmer** [comment]
There is a simple reason for that. Display lock is implemented by stopping updating the display. When the device is rotated there is no point in retaining display lock as the different display is regenerated with new data and will not be the same as before.
