### ISSUE TITLE
[RFE] when no tone is detected, show no tone

### ISSUE THREAD

**Issue by genodeftest** [billthefarmer/tuner#42]
Steps to reproduce:
1. open the app
2. have a quiet environment
3. have a look at Tuner's display

What happens:
![Screenshot_20201009-082230](https://user-images.githubusercontent.com/934401/98439936-b030da00-20f5-11eb-8f28-1c1084303448.png)
Several values are being displayed:
* A tone: C_0
* a difference: +0.00¢
* ideal frequency of the tone: 0.00Hz
* real frequency of the tone: 0.00Hz
* delta: +0.00Hz
* Concert pitch 440.00 Hz
* the musical note (shows C_0)
* the horizontal delta scale

What should happen:
The only correct info here would be the concert pitch. All other info should go away if no tone has been detected yet.
Rationale: Showing a tone which is not present can mislead users, especially if the microphone is not correctly working or their tone volume is too low.

Version info:
Tuner 1.37 on Android 9 patchlevel 2020-10-01

**Comment by billthefarmer** [comment]
When there is no signal:
 * No signal can be heard
 * There is no signal in the level display in the toolbar
 * There is no signal in the scope display
 * There is no signal in the spectrum display
 * The measured frequency display shows 0.00Hz
 * The reference frequency display shows 0.00Hz
I think it's pretty clear there's no signal.
