### ISSUE TITLE
white screen on app launch

### ISSUE THREAD

**Issue by 532910** [billthefarmer/tuner#43]
White flash burns eyes:
![ScreenRecord-2020-12-12-02-57-51](https://user-images.githubusercontent.com/14617699/101965493-e944f880-3c25-11eb-94bf-efaf5eb332da.gif)
Siggen has no such flash.
v1.37, android 10

**Comment by billthefarmer** [comment]
Android starts all apps with a blank white screen, even in dark mode, before they get a chance to do anything. The Tuner app has umpteen preferences to read to find out whether it should be in dark mode before it can display anything. The Siggen app only has a couple, so it's quicker. The Siggen app flashes white as well on my android 10 Samsung tablet on startup, but not on my android 7.1 Moto G.

**Comment by 532910** [comment]
> Android starts all apps with a blank white screen, even in dark mode, before they get a chance to do anything.

It's not true. There apps that start with a dark screen. Check other apps like Orgzly, Binary Eye or Car Report for example.

**Comment by 532910** [comment]
https://stackoverflow.com/questions/19738879/white-background-when-android-app-start-up

**Comment by billthefarmer** [comment]
You're quite correct, if you specify a dark theme for the app, you get a dark screen. However my apps default to the android default theme, which was, when they were developed, `android:Theme.Material.Light.DarkActionBar`, and probably still is, and offer the option in the settings of a dark theme. So they have to read the settings to change theme.

**Comment by 532910** [comment]
> have to read the settings

I belive there is nothing wrong to start with a dark background even for a white theme.

**Comment by billthefarmer** [comment]
True, but then I'd have to invert the logic on my apps to default to dark and offer light as an option. I've got no idea how many users use a dark theme, how many use light, and how many don't bother to change it or even look. It looks to me from your screen grab that the brightness is quite high.

**Comment by billthefarmer** [comment]
Something completely different &ndash; on my Samsung tablet, in both android 9 and 10, in the numerical display, the sharp and flat sign are shown in exactly the same shade of 3D dark grey in both light and dark themes. Does that happen on your device?

![Screenshot_20201213-104959_Tuner 1](https://user-images.githubusercontent.com/3448386/102009698-277b0e80-3d31-11eb-81c1-d489d210c8a7.jpg)

**Comment by 532910** [comment]
> but then I'd have to invert the logic on my apps to default to dark and offer light as an option

Is it possible to set start screen to black, but have a light theme by default?

> I've got no idea how many users use a dark theme, how many use light, and how many don't bother to change it or even look.

As well as how many people use your apps, but why does it matter? (:

> It looks to me from your screen grab that the brightness is quite high.

The brightness is minimum, you can't figure it out from a screen record, of course. (The same you can't take it from a screenshot.) (:

> Does that happen on your device?

No. Sharp and flat signs has the same color as the other text in both light and dark themes on my OP3T on LineageOS 17.1 based on Android 10.
![image](https://user-images.githubusercontent.com/14617699/102963935-724c1180-44fb-11eb-9e93-8e6f71fa0907.png)![image](https://user-images.githubusercontent.com/14617699/102963942-75470200-44fb-11eb-97dd-31bdcb1e07d9.png)
v1.37 from F-Droid
