### ISSUE TITLE
auto theme selection

### ISSUE THREAD

**Issue by 532910** [billthefarmer/tuner#44]
Please add support to use "system" theme.

**Comment by billthefarmer** [comment]
That's a bit problematical. I keep my apps small and lightweight by not using google supplementary and support libraries, which would be required. I also tend to ignore the android developers continually moving goalposts.

There are a number of icons in this app which switch between light and dark automatically using the provided attributes and style system with no action required apart from switching theme. There is no provision for that that I can see.
