### ISSUE TITLE
Accidentals don't adapt to dark theme

### ISSUE THREAD

**Issue by Glitchy-Tozier** [billthefarmer/tuner#46]
This happens pretty much in every place where sharp ♯and♭show up.

Screenshots:
![Screenshot_20210629-224738_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123907409-2381a780-d976-11eb-8063-c6d727ac2960.jpg)
![20210630_073022.jpg](https://user-images.githubusercontent.com/59611881/123907422-27adc500-d976-11eb-9a92-6e330fdce10e.jpg)
![Screenshot_20210630-073335_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123908575-fd5d0700-d977-11eb-9267-6c19eaede05c.jpg)

By the way, you've created a really nice tuner!  :)

**Comment by billthefarmer** [comment]
Yes that's true, it happens on my Samsung tablet. There's not a lot I can do about it as I am using the default font in all cases except for the staff display, which uses shapes. I don't know if it is a Samsung issue or an android version issue, but the characters appear to have been designed to work in both light and dark mode and are 3-D.

**Comment by Glitchy-Tozier** [comment]
Right, I also use a Samsung phone:
Samsung Galaxy S9
Android version 10

So are you saying this doesn't happen on other phones?

**Comment by billthefarmer** [comment]
It doesn't happen on Motorola phones running android 7.12 or emulators running android 10 and 11. Just to prove it's generic, here's a screenshot from my tablet of an editor with text from the tuner copy to clipboard facility. It even overrides the green text.

![Screenshot_20210630-123200_Editor 1](https://user-images.githubusercontent.com/3448386/123956339-7ffabc00-d9a2-11eb-9bab-ab5c801d8edd.jpg)

**Comment by Glitchy-Tozier** [comment]
♭♮♯


Oh, so you're using some kind of emojies instead of normal icons, right?

In that case, the bug makes sense to me; emojies don't adapt their colors to the system theme.

What about using actual icons that you could color according to the theme?
This might even improve the styling as you wouldn't use 3d-looking accidentals with an otherwise flat app.

**Comment by billthefarmer** [comment]
No, I'm using the standard Unicode font that includes musical characters along with hundreds of others. **Samsung** are using emojis or whatever in what should be the standard font.

**Comment by Glitchy-Tozier** [comment]
That's unfortunate. There still is tge possibility of actually using icons, but i imagine that's not very elegant, especially with changing font-sizes.

**Comment by billthefarmer** [comment]
I don't intend to attempt to fix a problem caused by Samsung's dubious font.

**Comment by Glitchy-Tozier** [comment]
Makes sense.
Closing this issue then.
