### ISSUE TITLE
Use German note-system when language is German.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [billthefarmer/tuner#47]
It's great that your app supports other languages such as German.

However, most (if not all) German-speaking countries use the German notation system which goes
```
g
        g flat
a
        b
h
c
```
instead of 
```
g
        g flat
a
        b flat
b
c
```
(Apparently quite a few non-German countries use it as well, but my knowledge on that is limited.)

I suggest using the german notatioms system when displaying the german translation of the app.

Here's a small wikipedia-article regarding notation-systems to back up my xescription of German notation: https://en.m.wikipedia.org/wiki/Key_signature_names_and_translations

**Comment by billthefarmer** [comment]
The app already supports the Do Re Mi system (Solfège), I don't propose to make it even more complicated. I don't do the translations for my apps, I gratefully accept and incorporate them when they are offers. The contributor who did the German translation did not translate the lists of note characters.

**Comment by Glitchy-Tozier** [comment]
In what way would that make things more complicated? (except on the developers side of course)

**Comment by billthefarmer** [comment]
This is an open source app. Anyone is free to clone it and produce a version using the German note system. What is complicated is switching between the two systems and determining when to use the German system.

Out of interest does the iStrobosoft tuner app or do small handheld electronic tuner devices use the German system in Germany?

**Comment by Glitchy-Tozier** [comment]
> Out of interest does the iStrobosoft tuner app or do small handheld electronic tuner devices use the German system in Germany?

#### iStrobosoft tuner app
This app requires a purchase so i unfortunately can't tell you for certain.

#### Handheld tuners
I actually couldn't find the one tuner i had at home so I can't give you guaranteed information. That being said, I'd be more surprised if i found a tuner with the English system. More than 95% of people use the German system and I've never met a single person that used the English system. I remember running into tons of misunderstandings with other musicians when i switched to the English system for a while.
Those experiences make me think the following: Unless they are tuners that imported from some other country because they were cheaper, most tuners you can find should only use the German notation.

**Comment by Glitchy-Tozier** [comment]
> What is complicated is switching between the two systems and determining when to use the German system.

Is it difficult to detect what language the app is currently displaying? If no, i have a slick implementation proposal:
1. Detect the app's language and only display the English notation unless the language is German.
2. Adapt the settings:
You already use popups in the settings.
I suggest adapting the Solfége-option to let it trigger a popup, just as you do with the Key-option.
There we can place a list with the following options:
  - Auto (the default behaviour)
  - English
  - German
  - Solfége

**Comment by billthefarmer** [comment]
The problem with using the locale or language is that the system is also possibly used in Eastern Europe and Scandinavia, but is falling into disuse in some areas, according to the [Wikipedia page](https://en.wikipedia.org/wiki/Key_signature_names_and_translations). I have tested an implementation which changes the display in the same way as the Solfège option.

![Screenshot_20210702-151319 1](https://user-images.githubusercontent.com/3448386/124300565-9ea1b400-db56-11eb-9844-c60acb773643.png)

![Screenshot_20210702-151416 1](https://user-images.githubusercontent.com/3448386/124301245-71093a80-db57-11eb-9535-809fbaedd643.png)

**Comment by Glitchy-Tozier** [comment]
> The problem with using the locale or language is that the system is also possibly used in Eastern Europe and Scandinavia, but is falling into disuse in some areas, according to the Wikipedia page.

What I'm saying is that if someone has set their phone to German (=Germany, Austria, Switzerland), there is a high likelihood that they prefer the German notation. Thus, it may be a positive user-experience if they got their system by default.
If you don't like the thought of implementing an language-adapting default notation, that would be unfortunate but not a deal-breaker though, as long as we offer some manual way of switching. 

> I have tested an implementation which changes the display in the same way as the Solfège option.

Perfect, that pretty much sounds like what I wanted to suggest by my second implementation-proposal. :)

> Screenshot
> Screenshot

They look really good.
