### ISSUE TITLE
Visibly disable key-setting when using equal temperment

### ISSUE THREAD

**Issue by Glitchy-Tozier** [billthefarmer/tuner#48]
To me, it was really confusing what i was supposed to do with that key-setting when using equal temperment.

To avoid this, i suggest disabling the key setting when equal temperment tuning is used.

Implementations I can think of:
1. Grey it out (might be difficult in dark mode)
1. Make it invisvisible, resulting in only the temperment-opion being there.
2. Make it unclickable and add a big **Not used in equal temperment** text across the setting.

Screenshots:
![Screenshot_20210629-225133_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123909184-f1be1000-d978-11eb-8e20-8b8e69433950.jpg)
![Screenshot_20210629-225157_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123909196-f4b90080-d978-11eb-90bc-f6b6d5fc3a8e.jpg)

**Comment by billthefarmer** [comment]
OK, I will look at that.

**Comment by Glitchy-Tozier** [comment]
Great!  :)

**Comment by billthefarmer** [comment]
OK, that works, will be in the next version.

**Comment by Glitchy-Tozier** [comment]
Great!

**Comment by Glitchy-Tozier** [comment]
Jup, it worked.
