### ISSUE TITLE
i need help , looked ，contact me 

### ISSUE THREAD

**Issue by sowdf** [billthefarmer/tuner#49]
i use tuner , i find audio input , show hz ,do not 不及时

**Comment by billthefarmer** [comment]
Google translated the Chinese '不及时' as 'Not timely'. I don't understand.

**Comment by sowdf** [comment]
How much is your email

**Comment by sowdf** [comment]
Your bed ？？？？

**Comment by sowdf** [comment]
I found the app can't update notes

**Comment by sowdf** [comment]
my email 229555644@qq.com ，Can you concat me ?????

**Comment by billthefarmer** [comment]
[119 people](https://github.com/billthefarmer/tuner/stargazers) currently have starred this app, Several of them appear to be Chinese. I would suggest you ask one of them for help.
