### ISSUE TITLE
Some features are unusable when animation are turned off

### ISSUE THREAD

**Issue by grizzlyfute** [billthefarmer/tuner#56]
Hello,

On recent android device, user as the possibility to turn off animations thought android parameters (Accessibility scope). This resulting as the following feature stop working :
- SignalView
- Staff
- Strobe
- Meter

The cause of the problem is the use of the _ValueAnimator_ object, used as a "clock". Normally this object fire every 10 ms, and update draw by trigger the invalidate event. This repeat is done indefinitely in the current project configuration.
When animation are disabled, object fire only two time with the minimal and maximal value, even it is configured to be repeated indefinitely, resulting of a freeze of concerned view.

I suggest to force animation trigger on audioProcess loop, after computation of the audio values, when animation are disabled. It may lose some fluidity because loop may run around 10 fps, but fix the broken feature. The concerned view not needed to be updated if audio value not changed, and losing fps may be not visible. In the other hand, the fix should preserve the previous behavior of fps when animation still enabled.

Pull request of this work will follow.

**Comment by grizzlyfute** [comment]
Pull request https://github.com/billthefarmer/tuner/pull/57

**Comment by billthefarmer** [comment]
It might be better, IMHO, to use a timer as I have done with the [windows](https://github.com/billthefarmer/ctuner/blob/master/windows/Tuner.cpp#L377) and [swift](https://github.com/billthefarmer/ctuner/blob/master/swift/AppDelegate.swift#L186) versions, although I did use the audio loop in the [Linux](https://github.com/billthefarmer/ctuner/blob/master/linux/tuner.cpp#L856) version because I couldn't find a suitable timer in GTK.

**Comment by grizzlyfute** [comment]
I am not having looking Linux/Windows version before starting the dev, as I saw the problems on (new) android devices.

Yes, I could use a timer - and i can do it if necessary -. The work may be improved. I choose to use the _processAudio_ loop for the following reasons
- Its was this way the scope and display (upper items) work. 
- The most of items does not need to be redraw until the audio computation is finished. IMHO, it is useless to trig invalidate if no data are modified. The audio process loop takes between 60 and 100 ms to cycle. A 30 fps timer have 33 ms of period (AnimatorValue run at 10 ms).  So, data can not be updated as quickly the animation timer will occurs. Redraw will waste CPU time.
- Some components as meter or scope take advantage of the ValueAnimator timer, and doing a smooth animation effect by keeping the mean of 20 latest values. Unless I use a 10 ms timer, this animation will be degraded. In non animated mode, I compensate this by keeping a 200 ms (20 * 10 ms) of a means of latest value. The effect in screen appears slightly different.

**Comment by billthefarmer** [comment]
You appear to have misunderstood how the app works. The animation loop in the meter, strobe and signal indicator are using an animation as an easy way to provide a repeating timer to allow the smoothing algorithm to move they meter pointer, say, smoothly from one position to another. Therefore it needs to run continuously, as does the animation I have used. The views do not use the output of the animation, only the timing. I am investigating dispensing with the animations and using either a timer or the delaying functions instead.

**Comment by grizzlyfute** [comment]
Hello,
I have well understand the purpose of the ValueAnimator, notably its role in the animation. (And maintain that object does not need to be redraw if nothing appears). This object is designed to provide an animation, not a timer, and should be reconfigured/restarted (reset start and stop value + duration) each time an audio value change and stop when cursor reach the final position. But this approach complexity the animated objects. 

I agree with you that the use of the timer will be the simplest way to solve, preserving exactly the same behavior of the application and be independent of animation setting. It do not touch the code structure. In this case, a single timer running on UI loop may trigger the few items requiring an animation.

Should I update the pull request ?

**Comment by billthefarmer** [comment]
No thank you, I have made the required changes.

**Comment by billthefarmer** [comment]
When I wrote this app, some years ago, I was concerned that the simple FFT might be a resource hog, so I profiled it on a Nexus 7 and found out that drawing the spectrum used the most resources. So I redesigned the spectrum algorithm and fixed it. I have just tested the latest version with my changes on the same Nexus 7, more than ten years old, and find that the app uses about 36% of CPU and the rendering usage is minimal compared to the rest of the app. On a Pixel 3A it uses about 8 or 9%.

![CPU](https://user-images.githubusercontent.com/3448386/220328644-ca6fa272-7620-479b-97ee-5bead2817101.png)

**Comment by grizzlyfute** [comment]
OK. Thanks for the requiert change and the benchmark summary. Fourrier and Spectrum make load on cpu. There as nothing to do. The timer are not loading the cpu because phone use its graphical resource to draw (it is designed for it !).
