### ISSUE TITLE
Copycat/Clone of Tuner on Google Play

### ISSUE THREAD

**Issue by Poussinou** [billthefarmer/tuner#58]
Hi @billthefarmer 

I just found this copycat of Tuner on Google Play https://play.google.com/store/apps/details?id=org.billthefarmer.thuir from [this developer](https://play.google.com/store/apps/developer?id=Schnupfeld).

This copycat is full of ads, and it clearly doesn't respect the GNU GPL v3. The developer's page is full of other copycats of open source apps, themselves full of ads...

You can follow the procedure [here](https://github.com/TeamNewPipe/NewPipe/issues/539#issuecomment-1399222536) if you want to send a takedown request to Google Play.

**Comment by Poussinou** [comment]
He also copied your "Editor" app [here](https://play.google.com/store/apps/details?id=org.billthefarmer.edoter).

**Comment by billthefarmer** [comment]
The last time I reported one, they refused to take it down, so I did a negative review.
