### ISSUE TITLE
adaptive themed icon

### ISSUE THREAD

**Issue by andsofine** [billthefarmer/tuner#59]
android 13 adaptive themed icon
![IMG_20230423_191201.jpg](https://user-images.githubusercontent.com/99369164/233851301-f20ba0ca-5ccd-4bc2-8c95-dc2655136de9.jpg)

any chance for that?

**Comment by billthefarmer** [comment]
I am a retired Unix/Linux geek. I design and build my apps for function and on multiple platforms, in this case [Windows](https://github.com/billthefarmer/ctuner), [MacOS](https://github.com/billthefarmer/ctuner/tree/master/swift), [Linux, Raspbian](https://github.com/billthefarmer/ctuner/tree/master/linux), Android. They all use the same icon. I don't follow Google's constantly moving goalposts and don't put my apps on anyone's app store. If you don't like the appearance of my app icons, get a launcher which lets you change app icons or don't put it on the home screen. See https://github.com/billthefarmer/diary/issues/182, https://github.com/billthefarmer/sig-gen/issues/18, https://github.com/billthefarmer/scope/issues/21.
