### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by ChristopheVersieux** [billthefarmer/tuner#6]
Hello,

I would like to work on this project and improve it for personnal use.
I have already converted the project in Android Studio,n used Fragments, etc, but would like to know if some people are still alive here and interested in PR and improvements.

Thank a lot for any feedback.

**Comment by billthefarmer** [comment]
Hi
The project is active, the last update was in May. Your fork is out of date. When I wrote this app Android Studio didn't exist, and I have no reason to update the sources other than bug fixes and in response to requests. As you have already forked it, feel free to develop it further. If you have not already done so, look at the closed issues, one of them has more info on the algorithms used.
