### ISSUE TITLE
Request for APK

### ISSUE THREAD

**Issue by hoschi-it** [billthefarmer/tuner#60]
Hi,
Thanks for developing and maintainig this great app!
If you don't mind, I'd love to get the apk file for the latest version.

## Why?
I'm trying to get rid of third parties (i.e. f-droid) between my device and app developers.
Every middleman adds to the complexity and increases vulnerability towards security threads.

Thanks.
Hoschi

**Comment by billthefarmer** [comment]
See https://github.com/billthefarmer/editor/issues/198 and subsequent comments.

**Comment by hoschi-it** [comment]
Thanks!
