### ISSUE TITLE
Tuner don't work 

### ISSUE THREAD

**Issue by lascapi** [billthefarmer/tuner#7]
Hello :-) 
Thank's for your work !! 
I can't use Tuner because spectrum work fine, but other diplay don't work !! I don't know why ? 
I'm on android 4.2 and Tuner 1.10 (installed with f-droid).

Any suggestion ?!

**Comment by billthefarmer** [comment]
I don't know why it doesn't work, you haven't given enough information. You can test it using my sig-gen app here: https://github.com/billthefarmer/sig-gen, also on F-Droid, which will run in the background, or the Windows or Mac version here: https://github.com/billthefarmer/audiotools.

Both sig-gen apps produce a 1KHz sine wave tone initially. The tuner app should do something like this. You may have to turn the output level up a bit, check the signal indicator in the action bar, and the scope.

![screenshot_2016-07-22-14-56-54](https://cloud.githubusercontent.com/assets/3448386/17059504/706a3478-501d-11e6-8bf0-cec5865d6a6b.png)

**Comment by lascapi** [comment]
Hi !! This is a screenshoot with 1KHz sine wave !!  
![screenshot_2016-07-25-18-32-58](https://cloud.githubusercontent.com/assets/6562527/17109106/de4b1946-5296-11e6-936d-d4538751d716.png)

**Comment by billthefarmer** [comment]
I have tested this on two different emulators, one running android 4.1.2 and the other running 4.2.2. They both work correctly. What phone are you using, and is there any useful information in the log file, which may give me a clue?

**Comment by 9662** [comment]
Hello Bill. I'm afraid I'm experiencing the same problem as described above by @lascapi. I tried your signal generator at 880 kHz and also using my own voice via internal mic and headphones. Clearly the sound is being picked up but only the spectrometer updates, not the rest of the display. This is Android 4.2.1.

I'll upload my screenshots from the computer in a few hours, it's a bit of a faff doing from the phone, but the ones from @lascapi illustrate the issue perfectly.

**Comment by billthefarmer** [comment]
As I said above , I can't reproduce this problem. I can only investigate it with more information, like a traceback from the log file. You can get this using adb from the command line - adb logcat. Android continually produces a stream of log entries even when it's apparently idle, so the best strategy is to start it going before starting the tuner and if you see a sudden burst of activity then stop it using Control-C before it scrolls off the page. Tracebacks from the tuner will contain org.billthefarmer.tuner. I get log entries like this...

    I/ActivityManager(  497): Start proc org.billthefarmer.tuner for activity org.billthefarmer.tuner/.MainActivity: pid=2259 uid=10091 gids={50091}
    D/ActivityThread( 2259): handleBindApplication:org.billthefarmer.tuner
    D/ActivityThread( 2259): setTargetHeapUtilization:0.75
    D/ActivityThread( 2259): setTargetHeapMinFree:524288
    D/AudioPolicyManagerBase(  142): getInput() inputSource 1, samplingRate 11025, format 1, channelMask 10, acoustics 0
    D/AudioPolicyManagerBase(  142): getInput() returns input 427
    I/ActivityManager(  497): Displayed org.billthefarmer.tuner/.MainActivity: +929ms

**Comment by 9662** [comment]
Hello again!

I've just done a [log capture](https://github.com/billthefarmer/tuner/files/595476/tuner.txt) while singing a (very out of tune) A₄.

```bash
adb logcat -v time |grep tuner |tee tuner.log
```

And here's the screenshot I took while I was at it:

![screenshot_2016-11-16-18-53-15](https://cloud.githubusercontent.com/assets/13080040/20359172/f3f6f3c2-ac2e-11e6-8748-c471277984a8.png)

Hope this helps. Looks like a perfect tuning app, looking forward to use it.

Your tone generator is great too, that's what I am using in the meanwhile as a pitch reference. ☺

**Comment by billthefarmer** [comment]
I'm beginning to wonder if this problem is something to do with refreshing the display rather than the audio decoding. I have never seen the BufferQueue log entries you are getting before.

    I/BufferQueue(  131): [org.billthefarmer.tuner/org.billthefarmer.tuner.MainActivity](this:0x43591468,api:1) [queue] fps:31.34, dur:1021.12, max:51.04, min:21.44
    I/BufferQueue(  131): [org.billthefarmer.tuner/org.billthefarmer.tuner.MainActivity](this:0x43591468,api:1) [release] fps:31.76, dur:1007.54, max:59.37, min:19.62
I will investigate this.

**Comment by 9662** [comment]
That would be my guess, because the oscilloscope appears to be spot on, also if I switch to an input source with no signal, it flat lines (as it should).

**Comment by 9662** [comment]
I'm happy to test any APKs that you may want to build, btw. Just attach them to a comment in here if you rather wouldn't do a release.

**Comment by billthefarmer** [comment]
I've looked through the code again and can't see anything to change that is different from my other apps apart from using a ValueAnimator for animating the strobe, meter and signal indicator. Looking at your and @lascapi's screenshots, the signal indicator is working. Two things to try - touch the spectrum to turn off the zoom so you can see if there is any signal at all getting through and try it in landscape, which removes most of the dynamic displays. I have uploaded a zip file with a video of the tuner on my phone - Github won't upload MP4 files. I just whistled a Christmas carol at it.

[tuner.zip](https://github.com/billthefarmer/tuner/files/601453/tuner.zip)

**Comment by billthefarmer** [comment]
I have put some debug code in the audio processing function. Debug logging is turned on and off by a long touch on the scope display. The loop runs about ten times a second, so will produce a lot of log entries. The output should look like this...

    11-19 14:06:56.185 11123 11739 D Audio   : Read data, size = 1024
    11-19 14:06:56.185 11123 11739 D Audio   : Copy to buffer
    11-19 14:06:56.186 11123 11739 D Audio   : Filtered
    11-19 14:06:56.201 11123 11739 D Audio   : Windowed
    11-19 14:06:56.291 11123 11739 D Audio   : FFTed
    11-19 14:06:56.302 11123 11739 D Audio   : Processed
    11-19 14:06:56.303 11123 11739 D Audio   : Maximised
    11-19 14:06:56.303 11123 11739 D Audio   : Found
    11-19 14:06:56.303 11123 11739 D Audio   : Read data, size = 1024
    11-19 14:06:56.303 11123 11739 D Audio   : Copy to buffer
    11-19 14:06:56.304 11123 11739 D Audio   : Filtered
    11-19 14:06:56.318 11123 11739 D Audio   : Windowed
    11-19 14:06:56.408 11123 11739 D Audio   : FFTed
    11-19 14:06:56.419 11123 11739 D Audio   : Processed
    11-19 14:06:56.420 11123 11739 D Audio   : Maximised
    11-19 14:06:56.420 11123 11739 D Audio   : Not found
There are checks for invalid results which may have prevented the updating of the displays, but only if the calculations produce an invalid (NaN) result every time. If this is the case you will get log entries containing 'Invalid cf = NaN' or 'Invalid cents = NaN'. I have uploaded a debug version of the app.

[Tuner-debug.zip](https://github.com/billthefarmer/tuner/files/601575/Tuner-debug.zip)

**Comment by 9662** [comment]
I have run the debug APK, here's the logs obtained with:

```bash
adb logcat -v time |egrep "tuner|Audio" |tee tuner.log
```
 * Started with the application off-focus, switched focus to the app at around time `:06:13`
 * Switched debug on at around `:06:21`
 * Switched debug off at around `:06:45`
 * Dismissed the application at around `:06:49`

[tuner.log](https://github.com/billthefarmer/tuner/files/608554/tuner.log.txt)

Hope this helps.

**Comment by billthefarmer** [comment]
There are no audio debug entries in the log. Either you didn't succeed in installing the debug version or you didn't succeed in turning debug on or the audio debug logging isn't working. Because my apps are built by F-Droid using their app signature a debug app I build will have a different signature, so it won't install unless you uninstall the F-Droid version. You need a long press on the scope display until the debug on notification toast comes up. I could see in the log that toasts were displayed but not which ones.

**Comment by 9662** [comment]
Sorry, I'm such an idiot. I seem to have uploaded the wrong file last time.

This one below should be more relevant. Started with debug off, switched on at `:30:39` and back off at `:31:02`, shortly before the end of the capture. Two notes are sung, separated by more or less one second of silence.

[tuner-2016-11-25a.log.txt](https://github.com/billthefarmer/tuner/files/612498/tuner-2016-11-25a.log.txt)

**Comment by billthefarmer** [comment]
Well that tells me that the audio system is working but not producing any results, so I have put in some more debugging to try and find out why.

[Tuner-debug.zip](https://github.com/billthefarmer/tuner/files/614911/Tuner-debug.zip)

**Comment by 9662** [comment]
@billthefarmer apologies for taking so long to get back to you.

Here is my latest and greatest rendition of a D note (I think it was, not sure now):

[tuner-log.txt](https://github.com/billthefarmer/tuner/files/652605/tuner-log.txt)

I started debug mode a few seconds into the log, you should see the toast message. Capture expression was the same as before:

```bash
adb logcat -v time |egrep "tuner|Audio" |tee tuner.log
```

**Comment by billthefarmer** [comment]
I have looked at this, it tells me that the audio system is working, but producing garbage results. As I said above, I can't reproduce it on an emulator or any of the devices I have. So there's not much I can do about it.
The code I am using in the app is the same as that in the Windows, Mac and Linux apps I have written, all of which work fine. Why it won't work on the devices that you and @lascapi are using I don't know.

**Comment by 9662** [comment]
> it tells me that the audio system is working, but producing garbage results

The interesting bit however, is that the scope display appears to perform correctly both in terms of frequency (at least relative, if I compare, say, two notes one octave apart) and amplitude. Shouldn't that not be possible, were the audio input not be reliable (and do I get any prizes for a triple negative)?

**Comment by billthefarmer** [comment]
The scope is looking at the input buffer before any processing, the spectrum is looking at the output of the FFT, and the display is showing the results of the frequency calculations. If you get a nice stable scope display and the signal indicator in the toolbar shows enough signal the audio input system is working. The spectrum, if zoomed in will only show a display if there is a valid frequency to zoom in on. If not zoomed in it should show the output of the FFT. If the processor can't keep up, which happens in some of the emulators, the scope and spectrum displays are all over the place, and the display shows random numbers. One of the things I checked when I first developed this app was to make sure it wasn't using up too much of the processor. Here's a snapshot of the CPU usage on my Nexus 7 (2012), which is getting a bit dated now.

![cpu](https://cloud.githubusercontent.com/assets/3448386/21314680/374485d8-c5f0-11e6-9bfb-7df571c227f6.png)

As you can see, it's not using much CPU, while picking the hum of the fans on my desktop out of the noise. The problem with your device is that signals are getting through, but the results are rubbish:
12-14 20:03:28.373 D/Audio   (13428): Read data, size = 1024
12-14 20:03:28.374 D/Audio   (13428): Copy to buffer
12-14 20:03:28.374 D/Audio   (13428): Filtered
12-14 20:03:28.380 D/Audio   (13428): Windowed, dmax = 3645.0
12-14 20:03:28.419 D/Audio   (13428): FFTed
12-14 20:03:28.429 D/Audio   (13428): Processed
12-14 20:03:28.429 D/Audio   (13428): Maximised, max = 1.5732299495372148E-7
12-14 20:03:28.240 D/Audio   (13428): Not found, frequency = 5.389464866620297

That shows there's plenty of signal, the dmax value is from the signed  short input buffer, so it's out of 32768. The max value, which is from the output of the FFT, needs to be more than 0.5 for the rest of the system to work.

**Comment by 9662** [comment]
> That shows there's plenty of signal, the dmax value is from the signed short input buffer, so it's out of 32768. The max value, which is from the output of the FFT, needs to be more than 0.5 for the rest of the system to work.

Thanks for the explanation. So you think that the problem may occur somewhere within the [`fftr`](https://github.com/billthefarmer/tuner/blob/e1d7fe83e9cbc3dbd01dfd810db4f386ec709557/src/org/billthefarmer/tuner/MainActivity.java#L1268) function?

**Comment by billthefarmer** [comment]
Yes you are correct. What I don't know is what could cause the problem when everything else is working. As I said above, I have used this FFT in several apps on several platforms without a problem.

**Comment by 9662** [comment]
It looks like I forgot to mention this, but the tuner works just fine on a new, faster phone running Android 7. The exact same version does not work on the older, slower phone running Android 4-something I think. I very much suspect this is down to CPU speed, just a hunch though.
