### ISSUE TITLE
Translation ? 

### ISSUE THREAD

**Issue by lascapi** [billthefarmer/tuner#8]
How can I translate your app in french ? 
Are you agree with that ?

**Comment by billthefarmer** [comment]
See https://developer.android.com/guide/topics/resources/localization.html. Extract from this page...

Example:

Suppose that your application's default language is English. Suppose also that you want to localize all the text in your application to French, and most of the text in your application (everything except the application's title) to Japanese. In this case, you could create three alternative strings.xml files, each stored in a locale-specific resource directory:

1. res/values/strings.xml
    Contains English text for all the strings that the application uses, including text for a string named title.
2. res/values-fr/strings.xml
    Contain French text for all the strings, including title.

In the case of my app, all the strings are here: https://github.com/billthefarmer/tuner/blob/master/res/values/strings.xml. You can either...
* Fork the app on Github and add your own French strings.xml and rebuild the app
* Translate the strings that need translating in the English version, and send me the translated strings and I will make a new version with French translation.
