### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by susobaco** [billthefarmer/tuner#9]
Hi, thanks for your work and your posting the code in GPL. I would love to translate the application into Spanish. Do you have an online translation service or do I translate the files and send them to an email?

**Comment by billthefarmer** [comment]
@lascapi asked about translation to French here: https://github.com/billthefarmer/tuner/issues/8. There is some info there about translation. You can either fork the app or post the translated files here and I will put them in a new version. I like your avatar, I've got some Osbourne Veterano in the cupboard.

**Comment by susobaco** [comment]
Ok I will do it that way. Thanks, it's a "meme" in the drawing says "soborne" not "osborne". "Soborne" means "You bribe" is a protest for the abundant cases of corruption that there are in Spain

**Comment by susobaco** [comment]
Ah! my name is Suso Comesaña.
